[game]
modes = [
    "waves",
    # "debug",
    # "bench",
    # "laser_sight",
]

[display]
fullscreen = true
window_size_x = 800
window_size_y = 800
v_sync = false

[graphic]
decals = 128

[audio]
sources = 128

[controls]
mouse_sensitivity = 0.003
