[game]
difficulty = 1.0 # 0.8 - easy, 1.0 - medium, 1.2 - hard
map = "forest" # available maps: forest, test
level = 1 # starting level
modes = [
    "waves",
    # "debug",
    # "debug_tweaks",
    # "bench",
    # "test_bot_spread",
]

[display]
full_screen = true
window_size_x = 800
window_size_y = 800
v_sync = false

[audio]
sources = 32

[controls]
mouse_sensitivity = 0.003
