[game]
difficulty = 1.0
modes = [
    # "waves",
    "debug",
    # "test_bot_spread",
]

[display]
full_screen = true
window_size_x = 800
window_size_y = 800
v_sync = false

[audio]
sources = 0

[controls]
mouse_sensitivity = 0.003000000026077032
