[game]
scenario = "waves" # bench_zombies, test, test_bot_spread, waves
difficulty = 1.0 # 0.8 - easy, 1.0 - medium, 1.2 - hard
level = 1 # starting level
debug = false

[display]
mode = "borderless" # fullscreen, borderless, windowed
window_w = 800
window_h = 800
v_sync = false

[audio]
sources = 48

[controls]
mouse_sensitivity = 0.003
