
[package]
name = "world-generator"
edition = "2021"
authors = ["Aunmag <aunmag@gmail.com>"]

[dependencies]
anyhow = "1.0"
enumset = { version = "1.1", features = ["serde"] }
image = { version = "0.25", features = ["png"] }
rand = "0.8"
rand_pcg = "0.3"
regex = "1.8"
